---
title: "directional_chord_diagrams"
author: "RN7"
date: "May 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## directional_chord_diagrams

https://guyabel.com/post/animated-directional-chord-diagrams/

```{r message=FALSE}
# install.packages("migest")
library(migest)
library(tidyverse)

# time series: bilateral migration flow estimates
d0 <- read_csv(system.file("imr", "reg_flow.csv", package = "migest"))

# regional meta data
d1 <- read_csv(system.file("vidwp", "reg_plot.csv", package = "migest"))

```

## Tween data

```{r}
library(tweenr)

d2 <- d0 %>% 
  mutate(corridor = paste(orig_reg, dest_reg, sep = " -> ")) %>% 
  select(corridor, year0, flow) %>% 
  mutate(ease = "linear") %>% 
  tween_elements(time = "year0", group = "corridor", ease = "ease", nframes = 100) %>% 
  as_tibble()

```

100 observations for each corridor >>> one for each frame in animation.

more wrangling for plotting: 

```{r}

d2 <- d2 %>% 
  separate(col = .group, into = c("orig_reg", "dest_reg"), sep = " -> ") %>% 
  select(orig_reg, dest_reg, flow, everything()) %>% # reorder 
  mutate(flow = flow / 1e06)



```

Plots for each frame

```{r message=FALSE}
fs::dir_create("./plot_gif")

#install.packages("circlize")
library(circlize)

for (f in unique(d2$.frame)) {
  
  png(file = paste0("./plot_gif/globalchord", f, ".png"), 
      height = 7, width = 7,
      units = "in", res = 500)
  
  circos.clear()
  par(mar = rep(0, 4), cex = 1)
  circos.par(start.degree = 90, track.margin = c(-0.1, 0.1), 
             gap.degree = 4, points.overflow.warning = FALSE)
  
  # plot
  chordDiagram(x = d2 %>% filter(.frame == FALSE), 
               directional = 1, order = d1$region,
               grid.col = d1$col1, annotationTrack = "grid",
               transparency = 0.25, annotationTrackHeight = c(0.05, 0.1),
               direction.type = c("diffHeight", "arrows"), link.arr.type = "big.arrow",
               diffHeight = -0.04, link.sort = TRUE, link.largest.ontop = TRUE)
  
  # labels + axis
  circos.track(track.index = 1, bg.border = NA, panel.fun = function(x, y) {
    
    xlim = get.cell.meta.data("xlim")
    sector.index = get.cell.meta.data("sector.index")
    reg1 = d1 %>% filter(region == sector.index) %>% pull(reg1) 
    reg2 = d1 %>% filter(region == sector.index) %>% pull(reg2)
    
    circos.text(x = mean(xlim), y = ifelse(is.na(reg2), 3, 4),
                labels = reg1, facing = "bending", cex = 1.1)
    circos.text(x = mean(xlim), y = 2.75, 
                labels = reg2, facing = "bending", cex = 1.1)
    circos.axis(h = "top", labels.cex = 0.8, 
                labels.niceFacing = FALSE, labels.pos.adjust = FALSE)
    
  })
  
  dev.off()
}


```


Create actual GIF from ~frame images

```{r}
library(magick)

img <- image_read(path = "./plot_gif/globalchord0.png")

for (f in unique(d2$.frame)[-1]) {
  
  img0 <- image_read(path = paste0("./plot_gif/globalchord", f, ".png"))
  img <- c(img, img0)
  
  message(f)
  
}

img1 <- image_scale(image = img, geometry = "720x720")

ani0 <- image_animate(image = img1, fps = 10)

image_write(image = ani0, path = "./plot_gif/globalchord.gif")


```




















