---
title: "Untitled"
author: "RN7"
date: "August 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(engsoccerdata)
```






```{r}
LIV_raw <- rbind(england, england_current()) %>% 
  filter(Season %in% c(1992:2015)) %>% 
  filter(home == "Liverpool" | visitor == "Liverpool") 

LIV <- LIV_raw %>% 
  janitor::clean_names() %>% 
  mutate(totalpts = 3*sum(gf>ga) + sum(gf == ga))

glimpse(LIV)


glimpse(england_current())

seasons <- 1992:2017

epl_standings_list <- seasons %>% 
  map(~ maketable(df = england, Season = .x, tier = 1, pts = 3)) %>% 
  set_names(seasons)

epl_standings_list$`1992`$Pts

epl_standings_list$`1992` %>% filter(Pts == max(Pts))


prem_winners <- map_df(epl_standings_list, ~ .x %>% filter(Pts == max(Pts)))


bind_rows(epl_standings_list, .id = "season") %>% 
  filter(Pos == "1") %>% 
  glimpse()


```




```{r}
# grab manager list
library(polite)
library(rvest)

session <- bow("https://en.wikipedia.org/wiki/List_of_Liverpool_F.C._managers")

print(session)
# good to go!
#//*[@id="mw-content-text"]/div/table[2]

library(lubridate)

lfc_managers_raw <- scrape(session) %>% 
  html_nodes(xpath = "//*[@id='mw-content-text']/div/table[2]") %>% 
  html_table(fill = TRUE, header = TRUE) %>% 
  flatten() %>% 
  as_tibble() %>% 
  slice(-1) %>% 
  select(Name, From, To)

lfc_managers_clean <- lfc_managers_raw %>% 
  janitor::clean_names() %>% 
  mutate(name = case_when(
    str_detect(name, "William") ~ "William Edward Barclay, John McKenna",
    str_detect(name, "EvansG") ~ "Roy Evans, Gerard Houllier",
    TRUE ~ name)) %>% 
  mutate(name = str_replace_all(name, "\\*", "")) %>% 
  mutate(from = parse_date_time(from, orders = "%d/%m/%Y"))


lfc_managers_clean %>% mutate(from_year = year(from)) %>% glimpse()


```




```{r}
library(colorr)
library(ggimage)
library(gganimate)

seasons <- 1992:2016

lfc_standings_list <- seasons %>% 
  map(~ maketable(df = england, Season = .x, tier = 1, pts = 3)) %>% 
  set_names(seasons) %>% 
  bind_rows(., .id = "season") %>% 
  filter(team == "Liverpool") %>% 
  mutate_at(vars(-matches("team")), as.numeric)   # all cols except team == numeric!

glimpse(lfc_standings_list)

lfc_logo <- 
  data.frame(image = "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg")


lfc_standings_list %>% 
  ggplot(aes(season, Pos, group = team)) +
  geom_path() +
  geom_image(aes(season, Pos, image = lfc_logo$image), size = 0.035) +
  scale_y_reverse(limits = c(22, 1), expand = c(0, 0), 
                  breaks = c(1, 2, 3, seq(4, 22, by = 2))) +   
  # need to reverse LIMITS as well!
  scale_x_continuous(breaks = scales::pretty_breaks(10)) +
  geom_hline(yintercept = 4, color = "green") +
  geom_hline(yintercept = 20, color = "red") +
  theme_bw() +
  transition_time(time = season)


# add managerial stints in differnt color shades >>> geom_rect()?

```




all teams

```{r}
seasons <- 1992:2016

league_standings_list <- seasons %>% 
  map(~ maketable(df = england, Season = .x, tier = 1, pts = 3)) %>% 
  set_names(seasons) %>% 
  bind_rows(., .id = "season") %>% 
  mutate_at(vars(-matches("team")), as.numeric)   


```


```{r}
league_standings_list %>% 
  janitor::clean_names() %>% 
  group_by(team) %>% 
  summarize(avgpos = median(pos) %>% round(digits = 1)) %>% 
  arrange(avgpos) %>% 
  top_n(-6, wt = avgpos) %>% 
  select(team) %>% as_vector() -> top_6

league_standings_list %>% 
  janitor::clean_names() %>% 
  filter(season < 2000) %>% 
  group_by(team) %>% 
  summarize(avgpos = median(pos) %>% round(digits = 1)) %>% 
  arrange(avgpos) %>% 
  top_n(-6, wt = avgpos)
  

league_standings_list %>% 
  janitor::clean_names() %>% 
  filter(season > 2009) %>% 
  group_by(team) %>% 
  summarize(avgpos = median(pos) %>% round(digits = 1)) %>% 
  arrange(avgpos) %>% 
  top_n(-6, wt = avgpos)

league_standings_list %>% 
  janitor::clean_names() %>% 
  group_by(team) %>% 
  mutate(avgpos = median(pos) %>% round(digits = 1)) %>% 
  ungroup() %>% 
  mutate(top6 = case_when(
    team %in% top_6 ~ TRUE,
    TRUE ~ FALSE
  )) %>% 
  ggplot(aes(season, pos, group = team)) +
  geom_path(aes(color = team)) +
  gghighlight::gghighlight(top6 == TRUE) +
  geom_point() +
  scale_y_reverse(limits = c(22, 1),  
                  breaks = c(1, 2, 3, seq(4, 22, by = 2))) +   
  # need to reverse LIMITS as well!
  scale_x_continuous(breaks = scales::pretty_breaks(10)) +
  nord::scale_color_nord(palette = "moose_pond") +
  geom_hline(yintercept = 4, color = "green") +
  geom_hline(yintercept = 20, color = "red") +
  theme_bw()


```




```{r}

league_standings_list %>% 
  janitor::clean_names() %>% 
  group_by(team) %>% 
  mutate(avgpos = mean(pos) %>% round(digits = 1)) %>% 
  ggplot(aes(season, pos, group = team)) +
  geom_path(aes(color = team), show.legend = FALSE) +
  gghighlight::gghighlight(mean(avgpos) < 5) +
  geom_point() +
  scale_y_reverse(limits = c(22, 1),  
                  breaks = c(1, 2, 3, seq(4, 22, by = 2))) +   
  # need to reverse LIMITS as well!
  scale_x_continuous(breaks = scales::pretty_breaks(10)) +
  geom_hline(yintercept = 4, color = "green") +
  geom_hline(yintercept = 20, color = "red") +
  theme_bw()




league_standings_list %>% 
  ggplot(aes(season, Pos, group = team)) +
  geom_path(show.legend = FALSE) +
  geom_point() +
  scale_y_reverse(limits = c(22, 1),  
                  breaks = c(1, 2, 3, seq(4, 22, by = 2))) +   
  # need to reverse LIMITS as well!
  scale_x_continuous(breaks = scales::pretty_breaks(10)) +
  geom_hline(yintercept = 4, color = "green") +
  geom_hline(yintercept = 20, color = "red") +
  theme_bw()


# use geom_segment instead of hline for rel/european for different eras

```












