---
title: "Untitled"
author: "RN7"
date: "July 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

http://lenkiefer.com/2018/07/21/connected-scatterplot/

```{r}
suppressPackageStartupMessages({
library(tidyquant)
library(tidyverse)
library(lubridate)
library(ggridges)
library(cowplot)
  library(extrafont)
})
```

# tidyquant data from FRED

```{r}
tickers <- data.frame(symbol=c("PCEPI","UNRATE","FEDFUNDS"),varname=c("pce.level","ur","fedfunds"))

df <- tidyquant::tq_get(c("PCEPI","UNRATE","FEDFUNDS"),get="economic.data", from="1959-01-01") 


df <- df %>% left_join(tickers, by = "symbol")

df %>% select(date, price, varname) %>% 
  spread(varname, price) %>% 
  mutate(pce = 100 * (pce.level / lag(pce.level, 12)) - 100) %>% 
  filter(!is.na(pce)) -> dfq

dfq <- dfq %>% 
  mutate(decade = paste0(10 * floor(year(date) / 10), "'s"))

```

## color schemes

```{r}
my_colors <- c(
  "green"      = rgb(103,180,75, maxColorValue = 256),
  "green2"      = rgb(147,198,44, maxColorValue = 256),
  "lightblue"  =  rgb(9, 177,240, maxColorValue = 256),
  "lightblue2" = rgb(173,216,230, maxColorValue = 256),
  'blue'       = "#00aedb",
  'red'        = "#d11141",
  'orange'     = "#f37735",
  'yellow'     = "#ffc425",
  'gold'       = "#FFD700",
  'light grey' = "#cccccc",
  'purple'     = "#551A8B",
  'dark grey'  = "#8c8c8c")


my_cols <- function(...) {
  cols <- c(...)
  if (is.null(cols))
    return (my_colors)
  my_colors[cols]
}


my_palettes <- list(
  `main`  = my_cols("blue", "green", "yellow"),
  `cool`  = my_cols("blue", "green"),
  `hot`   = my_cols("yellow", "orange", "red"),
  `mixed` = my_cols("lightblue", "green", "yellow", "orange", "red"),
  `mixed2` = my_cols("lightblue2","lightblue", "green", "green2","yellow","gold", "orange", "red"),
  `mixed3` = my_cols("lightblue2","lightblue", "green", "yellow","gold", "orange", "red"),
  `mixed4` = my_cols("lightblue2","lightblue", "green", "green2","yellow","gold", "orange", "red","purple"),
  `mixed5` = my_cols("lightblue","green", "green2","yellow","gold", "orange", "red","purple","blue"),
  `mixed6` = my_cols("green", "gold", "orange", "red","purple","blue"),
  `grey`  = my_cols("light grey", "dark grey")
)


my_pal <- function(palette = "main", reverse = FALSE, ...) {
  pal <- my_palettes[[palette]]
  
  if (reverse) pal <- rev(pal)
  
  colorRampPalette(pal, ...)
}


scale_color_mycol <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- my_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("colour", paste0("my_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}



scale_fill_mycol <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- my_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("fill", paste0("my_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}
```



## plot

```{r}
g1 <- ggplot(data=dfq, aes(x=pce,y=fedfunds,color=decade)) + 
  geom_point() + 
  theme_ridges(font_family="Roboto") + 
  geom_path() + 
  scale_color_mycol("mixed6") + 
  theme(legend.position="left")

g2 <- ggplot(data=dfq, aes(x=ur,y=pce,color=decade)) + 
  geom_point() + 
  theme_ridges(font_family="Roboto") + 
  geom_path() + 
  scale_color_mycol("mixed6") + 
  theme(legend.position="none")

g3 <- ggplot(data=dfq, aes(x=ur,y=fedfunds,color=decade)) + 
  geom_point() + 
  theme_ridges(font_family="Roboto") + 
  geom_path() + 
  scale_color_mycol("mixed6") + 
  theme(legend.position="none")

g1ts <- ggplot(data=dfq, aes(x=date,y=fedfunds,color=decade))+ 
  geom_line() + 
  theme_ridges(font_family="Roboto") + 
  scale_color_mycol("mixed6") + 
  theme(legend.position="none")

g2ts <- ggplot(data=dfq, aes(x=date,y=pce,color=decade)) + 
  geom_line() + 
  theme_ridges(font_family="Roboto") + 
  scale_color_mycol("mixed6") + 
  theme(legend.position="none")

g3ts <- ggplot(data=dfq, aes(x=date,y=ur,color=decade)) + 
  geom_line() + 
  theme_ridges(font_family="Roboto") + 
  scale_color_mycol("mixed6") + 
  theme(legend.position="none")

g.ts <- plot_grid(g1ts,g2ts,
                  g3ts,
                  ncol=1)

```
















