---
title: "Pie_Charts"
author: "RN7"
date: "October 27, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Who Ate All The Pie (Charts)?

#### Pie charts: Pros, Cons, Alternatives!







# Dot Plots ---------------------------------------------------------------


```{r}
library(tidyverse)


costchart <- tibble(expensetype = c("Operating", "Infrastructure & Capital", "Financing"), 
                        Y2006 = c(0.45, 0.32, 0.23),   # 
                        Y2007 = c(0.44, 0.32, 0.24),
                        Y2008 = c(0.40, 0.34, 0.26),
                        Y2009 = c(0.38, 0.32, 0.30),   # 
                        Y2010 = c(0.36, 0.36, 0.28),
                        Y2011 = c(0.37, 0.37, 0.26),
                        Y2012 = c(0.40, 0.38, 0.22))    # 

```

# turn into tidy data using reshape2 package :: melt() function!

```{r}
library(reshape2)
costgather <- costchart %>% 
  melt(id.vars = "expensetype",
       measure.vars = c("Y2006", "Y2007", "Y2008", "Y2009", "Y2010", "Y2011", "Y2012"),
       variable.name = "Year", value.name = "Percentage")
```

# works
```{r}
costchart %>% 
  melt(id.vars = "expensetype",
       measure.vars = c("Y2006", "Y2007", "Y2008", "Y2009", "Y2010", "Y2011", "Y2012"),
       variable.name = "Year", value.name = "Percentage")
```


# not work
```{r}
costchart %>% 
  melt(id.vars = "expensetype",
       measure.vars = "Y2006":"Y2012",
       variable.name = "Year", value.name = "Percentage")
```



# OR tidyverse :: gather() function!
```{r}
costchart %>% 
  gather(Y2006:Y2012, key = "year", value = "percentage")
```


# dotplot

```{r}
library(scales)


ggplot(costgather, aes(x = Percentage, y = reorder(expensetype, Percentage), group = Year)) +
  geom_point(aes(shape = Year, color = Year), size = 5) +
  scale_x_continuous(limits = c(0, 100), labels = percent_format()) +
  labs(x = "Percentages", y = NULL) +
  ggtitle("Dot plots instead!") +
  theme_bw() +
  theme(panel.grid.major.y = element_line(colour = "grey60"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = rel(1.1), face = "bold"),
        axis.ticks.y = element_blank(),
        legend.position = "top",
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.key.width = unit(3, "lines"))

```


```{r}

costgather %>% 
  ggplot(aes(x = reorder(expensetype, Percentage), y = Percentage), group = Year) +
  geom_point(aes(shape = Year, color = Year)) +
  coord_flip() +
  theme_bw()


```






# on one graph with facets:

```{r}
library(hrbrthemes)
library(scales)

ggplot(costgather, aes(x = Year, y = Percentage, group = expensetype)) +
  geom_line() + 
  facet_grid(. ~ expensetype) +
  theme(axis.text.x = element_text(angle = 45)) +
  scale_y_continuous(labels = percent_format)

my_data <- data.frame(
  task = c("Connect a stereo", "Create a mixed tape", "Program radio stations", 
           "Record on one side of a tape", "Program the CD player", 
           "Set the clock", "Set the timer to record", 
           "Listen to a song on a CD", "Listen to a tape", 
           "Listen to the radio"),
  Revised = c(8.8, 9.6, 7.7, 5.8, 2.6, 2.3, 2.2, 2.1, 2.2, 1.0),
  Original = c(18.6, 15.9, 11.3, 9.7, 6.4, 4.0, 3.7, 3.8, 2.6, 0.9))


library(reshape2)
my_data_long <- melt(my_data, id.vars = "task", 
                     measure.vars = c("Revised", "Original"),
                     variable.name = "type", value.name = "time")

```





# Pie Charts --------------------------------------------------------------

# 2006 chart

```{r}

costchart <- data.frame(expensetype = c("Operating", "Infrastructure & Capital", "Financing"), 
                        value = c(45, 32, 23))

bp <- ggplot(costchart, aes("", y = value, fill = expensetype)) + 
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=5)

pie <- bp + coord_polar("y", start=0) +
  theme(axis.text=element_blank(),
        axis.ticks= element_blank(), 
        panel.grid = element_blank(),
        axis.title = element_blank()) +
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=5) +
  labs(title = "Expense Breakdown (2006)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"), 
                    name="Expense Type",
                    labels=c("Infrastructure & Capital", "Financing", "Operating")) +
  guides(fill = guide_legend(reverse = TRUE))

pie

```


# 2009 chart

```{r}

costchart3 <- data.frame(expensetype = c("Operating", "Infrastructure & Capital", "Financing"), 
                         value = c(38, 32, 30))
bp3 <- ggplot(costchart3, aes("", y = value, fill = expensetype)) + 
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=5)
pdf("2009ExpensePie.pdf")
pie3 <- bp3 + coord_polar("y", start=0) +
  theme(axis.text=element_blank(),
        axis.ticks= element_blank(), 
        panel.grid = element_blank(),
        axis.title = element_blank()) +
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=5) +
  labs(title = "Expense Breakdown (2009)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"), 
                    name="Expense Type",
                    labels=c("Infrastructure & Capital", "Financing", "Operating")) +
  guides(fill = guide_legend(reverse = TRUE))

pie3

```



# 2012 reworked

```{r}

costchart4 <- data.frame(expensetype = c("Operating", "Infrastructure & Capital", "Financing"), 
                         value = c(44, 29, 27))

bp4 <- ggplot(costchart4, aes("", y = value, fill = expensetype)) + 
  geom_bar(width = 1, stat = "identity")
bp4
pdf("2012ExpensePieV2.pdf")

pie4 <- bp4 + coord_polar("y", start=0) +
  theme(axis.text.x=element_blank(),
        axis.ticks= element_blank(), 
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.title = element_blank()) +
  geom_text(aes(y = value/3 + c(0, cumsum(value)[-length(value)]), 
                label = percent(value/100)), size=5) +
  labs(title = "Expense Breakdown (2012)") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"), 
                    name="Expense Type",
                    labels=c("Infrastructure & Capital", "Financing", "Operating")) +
  guides(fill = guide_legend(reverse = TRUE))

pie4

```



