---
title: "Untitled"
author: "RN7"
date: "July 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

gist from: https://gist.github.com/Gedevan-Aleksizde/14e02581f1b4ca228d4f3d9337ee6049
- User: Gedevan-Aleksizde

- slightly modified to be more tidyverse-ish 

## packages

```{r}
library(ggplot2)
library(ggthemes)
library(dplyr)
library(rjson)
library(jsonlite)
library(tidyr)
library(purrr)

```

## import data

```{r}
tempera_tokyo <- jsonlite::read_json("data/temperature.json") %>% map(~unlist(.x))

```

## tidy data

```{r}
# 143 has many observations missing, elongate to length of previous (142) then fill them in with NAs
tempera_tokyo[[143]] <- c(tempera_tokyo[[143]], rep(NA, length(tempera_tokyo[[142]]) - length(tempera_tokyo[[143]])))

tempera_tokyo <- tempera_tokyo %>% set_names(1876:2018) %>% as_data_frame()

tempera_tokyo <- tempera_tokyo %>% 
  mutate(month_day = seq(as.Date("2018-06-01"), as.Date("2018-09-30"), by = "day")) %>% 
  gather(key = "year", value = "avg_temp", -month_day) %>% 
  mutate(avg_temp = as.numeric(avg_temp),
         year = as.integer(year),
         location = "Tokyo")

```

## plot_heat()!

```{r}
plot_heat <- function(data) {
  
  g <- ggplot(
    data %>% filter(between(month_day, as.Date("2018-06-01"), as.Date("2018-09-30"))),
    aes(x = month_day, y = year,
        fill = avg_temp, color = "grey")
  ) +
    geom_tile(color = "grey", width = 1, height = 1) +
    scale_fill_distiller(name = "日毎平均気温　（Celsius）", palette = "Spectral") +
    scale_y_reverse() +
    scale_x_date(date_labels = "%m-%d") +
    scale_color_discrete(guide = FALSE) +
    coord_equal() +
    theme_tufte() +
    theme(axis.title.y = element_text(angle = 0, vjust = 0.5))
  
  return(g)
  
}

```

## plot!

```{r}
# tile map
g <- plot_heat(tempera_tokyo)

g2 <- tempera_tokyo %>% 
  mutate(date = paste(as.character(year), format(month_day, "%m-%d"), sep = "-") %>% as.Date()) %>% 
  ggplot(aes(x = date, y = avg_temp, color = avg_temp)) +
  geom_line() +
  scale_color_distiller(name = "", palette = "Spectral") +
  labs(x="", y="日毎平均気温 (°C)",
       caption="数値は気象庁より\n https://www.data.jma.go.jp/gmd/risk/obsdl/index.php") +
  theme_pander()


```















