---
title: "Untitled"
author: "RN7"
date: "August 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(tibble)
library(dplyr)
library(unheadr)
library(purrr)
library(gganimate)
library(stringr)
```

```{r}
table1 <- tribble(
  ~Taxon,                                     ~Ecoregions,                      ~Macroniches,    ~Body_mass,
  "Erethizontidae",                                              NA,                                NA,            NA,
  "Chaetomys",                           "Atlantic Rainforest",              "Arboreal-herbivore",        "1300",
  "Coendou",                 "Atlantic Rainforest, Amazonia",   "Arboreal-frugivore, herbivore",   "4000–5000",
  "Echinoprocta",                                      "Amazonia",            "Scansorial-frugivore",         "831",
  "Erethizon", "Tundra grasslands, forests, desert scrublands",            "Scansorial-herbivore",  "5000–14000",
  "Sphiggurus",                           "Atlantic Rainforest",              "Arboreal-herbivore",   "1150–1340",
  "Chinchillidae",                                              NA,                                NA,            NA,
  "Chinchilla",                                         "Andes",            "Saxicolous-herbivore",     "390–500",
  "Lagidium",                                     "Patagonia",            "Saxicolous-herbivore",    "750–2100",
  "Lagostomus",                           "Pampas, Monte Chaco",         "Semifossorial-herbivore",   "3520–8840",
  "Dinomyidae",                                              NA,                                NA,            NA,
  "Dinomys",                                      "Amazonia", "Scansorial-frugivore, herbivore", "10000–15000",
  "Caviidae",                                              NA,                                NA,            NA,
  "Cavia",                      "Amazonia, Chaco, Cerrado",           "Terrestrial-herbivore",     "550–760"
)
```



tidy multiple headers in table


```{r}
table1_tidy <- table1 %>% untangle2(regex = "dae$", orig = Taxon, new = Family)

glimpse(table1)
glimpse(table1_tidy)

```


```{r}
longDat <- function(x) {
  
  x %>% 
    setNames(seq_len(ncol(x))) %>% 
    mutate(row = row_number()) %>% 
    tidyr::gather(column, value, -row) %>% 
    mutate(column = as.integer(column)) %>% 
    ungroup() %>% 
    arrange(column, row)
  
}

table1 %>% 
  setNames(seq_len(ncol(.))) %>% 
  mutate(row = row_number()) %>% 
  tidyr::gather(column, value, -row) %>% 
  mutate(column = as.integer(column)) %>% 
  ungroup() %>% 
  arrange(column, row) %>% 
  mutate(header=as.character(str_detect(value,"dae$"))) %>% 
  group_by(header) %>% 
  mutate(headerid = row_number()) %>% 
  mutate(celltype=
           case_when(
             header=="TRUE"~ as.character(headerid),
             is.na(header)  ~ NA_character_,
             TRUE~"data"
           )) %>% 
  ungroup() %>% 
  mutate(tstep="a")

long_tables <- map(list(table1,table1_tidy),longDat)

table1_tidy %>% 
  setNames(seq_len(ncol(.))) %>% 
  mutate(row = row_number()) %>% 
  tidyr::gather(column, value, -row) %>% 
  mutate(column = as.integer(column)) %>% 
  ungroup() %>% 
  arrange(column, row) %>% 
  mutate(header=as.character(str_detect(value,"dae$"))) %>% 
  filter(header==TRUE) %>% 
  distinct(value) %>% 
  mutate(gpid=as.character(1:n())) %>% 
  right_join(long_tables[[2]]) %>% 
  mutate(celltype=if_else(is.na(gpid),"data",gpid)) %>% 
  mutate(tstep="b")



```




```{r}
tab1_long_og <- long_tables[[1]] %>% 
  mutate(header=as.character(str_detect(value,"dae$"))) %>% 
  group_by(header) %>% mutate(headerid = row_number()) %>% 
  mutate(celltype=
           case_when(
             header=="TRUE"~ as.character(headerid),
             is.na(header)  ~ NA_character_,
             TRUE~"data"
           )) %>% ungroup() %>% mutate(tstep="a")

tab1_long_untangled <- long_tables[[2]] %>% 
  mutate(header=as.character(str_detect(value,"dae$"))) %>% 
  filter(header==TRUE) %>% distinct(value) %>% mutate(gpid=as.character(1:n())) %>% 
  right_join(long_tables[[2]]) %>% mutate(celltype=if_else(is.na(gpid),"data",gpid)) %>% 
  mutate(tstep="b")
```





```{r}
longTabs_both <- bind_rows(tab1_long_og,tab1_long_untangled)


glimpse(longTabs_both)
```

```{r}
ggplot(longTabs_both,aes(column, -row, fill = celltype)) +
  geom_tile(color = "black") + 
  theme_void()+facet_wrap(~tstep)+
  scale_fill_manual(values=c("#247ba0","#70c1b3","#b2dbbf","#ff1654","#ead2ac","gray"),
                    name="",
                    labels=c(c(paste("group",seq(1:4)),"data","NA")))
```





```{r}
ut_animation <-  
  ggplot(longTabs_both,aes(column, -row, fill = celltype)) +
  geom_tile(color = "black")+ 
  theme_void()+
  scale_fill_manual(values=c("#247ba0","#70c1b3","#b2dbbf","#ff1654","#ead2ac","gray"),
                   name="",
                   labels=c(c(paste("group",seq(1:4)),"data","NA")))+
  transition_states(
    states            = tstep, # variable in data
    transition_length = 1,   # all states display for 1 time unit
    state_length      = 1    # all transitions take 1 time unit
  ) +
  enter_fade() +             # How new blocks appear
  exit_fade() +              # How blocks disappear
  ease_aes('sine-in-out')  
```

